# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- dev

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '**\*.sln'
    feedsToUse: 'select'
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**\*.sln'
- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '**\*.sln'
- task: Npm@1
  inputs:
    command: 'install'
    workingDir: 'ClimbTrackClient'
- task: Npm@1
  inputs:
    command: 'custom'
    workingDir: 'ClimbTrackClient'
    customCommand: 'run build'
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: 'ClimbTrackClient\build'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/ClimbTrackClient.zip'
    replaceExistingArchive: true
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: true