// <auto-generated />
using System;
using ClimbTrackApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace ClimbTrackApi.Migrations
{
    [DbContext(typeof(ClimbTrackContext))]
    [Migration("20190727192142_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("ClimbTrackApi.Domain.Models.Activity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ExerciseId");

                    b.Property<int>("workoutID");

                    b.HasKey("ID");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("workoutID");

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("ClimbTrackApi.Domain.Models.Exercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<string>("Notes");

                    b.Property<int>("Reps");

                    b.Property<int>("Sets");

                    b.HasKey("Id");

                    b.ToTable("Exercises");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            Name = "Situps",
                            Reps = 2,
                            Sets = 1
                        },
                        new
                        {
                            Id = -2,
                            Name = "Super Thigh burn",
                            Reps = 12,
                            Sets = 2
                        },
                        new
                        {
                            Id = -3,
                            Name = "Super extra exercise",
                            Reps = 12,
                            Sets = 2
                        });
                });

            modelBuilder.Entity("ClimbTrackApi.Domain.Models.Workout", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("date");

                    b.Property<string>("name")
                        .IsRequired();

                    b.HasKey("ID");

                    b.ToTable("Workouts");
                });

            modelBuilder.Entity("ClimbTrackApi.Domain.Models.Activity", b =>
                {
                    b.HasOne("ClimbTrackApi.Domain.Models.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ClimbTrackApi.Domain.Models.Workout", "workout")
                        .WithMany()
                        .HasForeignKey("workoutID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
