export const CREATE_CLIMBING_SESSION = 'CREATE_CLIMBING_SESSION';
export const SET_CLIMBING_SESSIONS = 'SET_CLIMBING_SESSIONS';
export const SET_STYLES = 'SET_STYLES';
export const SET_AUTHENTICATED = 'SET_AUTHENTICATED';
export const SHOW_ERROR = 'SHOW_ERROR';
export const SET_SHOW_CLIMBLOGGER_MODAL = 'SET_SHOW_CLIMBLOGGER_MODAL';